## Basics

In [1]:
import torch

### Tensors

In [4]:
# Scalar
x=torch.empty(1)
print(x)

# 1D
x=torch.empty(5)
print(x)

# 2D
x=torch.empty(2,3)
print(x)

tensor([0.])
tensor([-1.0666e+14,  1.6633e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00])
tensor([[-1.0666e+14,  1.6633e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [15]:
# Ones
x=torch.ones(2,2)
print(x)


# Integers
x=torch.ones(2,2,dtype=torch.int)
print(x)


# Size
x=torch.empty(10,2)
print(x.size())


#  Initializing Tensor Directly from data
x=torch.tensor([1.0,0.5])
print(x)

# Addition
x=torch.rand(1,2)
y=torch.rand(1,2)
print(x+y)


# Inplace Addition
print(y)
y.add_(x)
print(y)


# Element Wise Multiplication
z=x*y
print(z.size())

z=torch.mul(x,y)
print(z.size())

# Matrix Multiplication
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[7, 8], [9, 10], [11, 12]])
c = torch.matmul(a, b)
print(a.size(),"*",b.size(),"=",c.size())

tensor([[1., 1.],
        [1., 1.]])
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.Size([10, 2])
tensor([1.0000, 0.5000])
tensor([[1.2793, 1.0891]])
tensor([[0.5075, 0.5449]])
tensor([[1.2793, 1.0891]])
torch.Size([1, 2])
torch.Size([1, 2])
torch.Size([2, 3]) * torch.Size([3, 2]) = torch.Size([2, 2])


In [14]:
x=torch.rand(5,3)
print(x)

# Slicing
print(x[:,1])

# Item()
print(x[1,1]) #in tensor form
print(x[1,1].item()) # scalar not a tensor


tensor([[0.7870, 0.8309, 0.0736],
        [0.0537, 0.7782, 0.9817],
        [0.9591, 0.1264, 0.7659],
        [0.6511, 0.3079, 0.4006],
        [0.7001, 0.8446, 0.2926]])
tensor([0.8309, 0.7782, 0.1264, 0.3079, 0.8446])
tensor(0.7782)
0.7782097458839417


### Reshaping
!![image.png](https://i.stack.imgur.com/ORqaP.png)

In [18]:
x=torch.rand(4,4)
print(x)

y=x.view(-1,8)
print(y)

tensor([[0.0041, 0.1609, 0.0165, 0.4877],
        [0.7163, 0.6417, 0.0228, 0.5389],
        [0.1670, 0.3177, 0.8396, 0.5349],
        [0.2955, 0.9079, 0.8595, 0.6270]])
tensor([[0.0041, 0.1609, 0.0165, 0.4877, 0.7163, 0.6417, 0.0228, 0.5389],
        [0.1670, 0.3177, 0.8396, 0.5349, 0.2955, 0.9079, 0.8595, 0.6270]])


In [29]:
# From Tensor to numpy
x=torch.ones(5)
print(x)

x_np=x.numpy()
print(x_np)

# 🔴🔴 Since both x and x_np are on CPU both point to the same location
# So modify one appears in both 
x.add_(1)
print(x)
print(x_np)


# From Numpy to Tensor
import numpy as np
x=np.ones(5)
print(x)

x_torch=torch.from_numpy(x)
print(x_torch)

# 🔴🔴 Same Note

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### CUDA

In [33]:
if torch.cuda.is_available():
    print("Using GPU")
    device=torch.device("cuda")
else:
    print("Using CPU")
    device=torch.device("cpu")

# Make tensor in GPU
x=torch.ones(5,device=device)
print(x)

# Move tensor to GPU
y=torch.ones(5)
y=y.to(device)

z=x*y # performed on GPU


# Move tensor to CPU
z=z.to("cpu")

Using GPU
tensor([1., 1., 1., 1., 1.], device='cuda:0')
